services:
  frontend:
    image: pethub-frontend
    container_name: pethub-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    # restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: pethub-backend
    container_name: pethub-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8070:8070"
    command: bash -c "yarn prisma migrate dev && yarn dev"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: pethub-database
    image: postgres:13
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
volumes:
  dev_postgres_data:
