# Use a base image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code to the working directory
COPY . .

# Expose a port (if needed)
EXPOSE 8070

# Define the command to run the application
CMD ["yarn", "start"]